### ISSUE TITLE
Is this against HIG?

### ISSUE THREAD

**Issue by CalebKierum** [jdisho/FlippingNotch#3]
Dont get me wrong I love this project but could someone actually ship an app with this? 
https://developer.apple.com/ios/human-interface-guidelines/overview/iphone-x/

"Don't use visual adornments like brackets, bezels, shapes, or instructional text to call special attention to these areas, either."

**Comment by jdisho** [comment]
Yes, that is correct! 
Apple does not embrace creating notch related UIs and I don't think that someone can ship an app with this.
